### ISSUE TITLE
KCP Algorithm

### ISSUE THREAD

**Issue by mindcat** [faern/librips#5]
I don't know what you are doing, but I leave a thing you should know. It may could help you :D
https://github.com/skywind3000/kcp

**Comment by jedisct1** [comment]
KCP is neat, but totally different from that project. 

That said, a KCP implementation in Rust would be great, if only for portability.

**Comment by mindcat** [comment]
Hmm, I see. :D
If you are about the KCP implementation in Rust. Here is:
https://github.com/en/kcp-rs
